// 2-Angular_Projects/Hackthon/angular-book-application-hackathon/src/app/components/header/header.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule,RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  isLoggedIn:boolean=false
}

<nav class="navbar navbar-expand-lg navbar-custom">
    <div class="container-fluid">
        <img src="" alt="">
      <a class="navbar-brand" href="#"><i class="bi bi-house-add-fill"></i>&nbsp;Smiles Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">User</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/adminDashboard">admin</a>
          </li>
          
        </ul>
        <form class="d-flex">
          <button class="btn btn-login me-2" routerLink="/login" >Login</button>
          <button class="btn btn-login me-2"  *ngIf="isLoggedIn"   routerLink="/login" >logout</button>

          <button class="btn btn-register"  routerLink="register" >Register</button>
        </form>
      </div>
    </div>
  </nav>

// 4-React_Projects/my_redux_based/src/Components/navigation/Header.jsx
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import React from 'react'
import { Link } from 'react-router-dom';

export default function Header() {
  return (
    <div>
         <Navbar expand="lg" bg="dark" data-bs-theme="dark">
      <Container>
        <Navbar.Brand href="#home"><i className="bi bi-bootstrap"></i> &nbsp;React-Bootstrap</Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
        <Nav className="me-auto">
            <Nav.Link href="#home"><i className="bi bi-house-add-fill"></i>&nbsp; Home</Nav.Link>
            <Nav.Link as={Link} to='/user'>User</Nav.Link>
            <Nav.Link href="#pricing">Admin</Nav.Link>
          </Nav>
          <Nav>
        <Nav.Link href="#features"><i className="bi bi-person-circle"></i>&nbsp;Login</Nav.Link>
        <Nav.Link href="#pricing"><i className="bi bi-file-earmark-person-fill"></i>&nbsp;Register</Nav.Link>
        </Nav>
        </Navbar.Collapse>
       
      </Container>
    </Navbar>
    </div>
  )
}
