// 2-Angular_Projects/news-api-angular/src/app/card/card.component.ts
import { Component } from '@angular/core';
import { NewsServiceService } from '../services/news-service.service';
import { ActivatedRoute } from '@angular/router';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';



@Component({
  selector: 'app-card',
  standalone: true,
  imports: [DatePipe,CommonModule,FormsModule],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css'
})
export class CardComponent {
  


  constructor(private newService:NewsServiceService,private route: ActivatedRoute){}
  id:any;
  articles: any[] = [];
 
  ngOnInit(){
    this.route.paramMap.subscribe(params => {
      this.id = params.get('id');
      console.log(this.id);
    });
    
    this.newService.getByQuery(this.id).subscribe((res)=> {

      this.articles = res.articles;
      console.log(res);
    })
  }

  
}


   <div class="container mainheader">
    <h3 class="heading" >Related : {{id | titlecase}} </h3>
    <!-- <h3 *ngIf="id!==0" class="heading">General</h3>  -->
    
    <div class="row">
        <div class="col-md-4 custom-div-dynamic" *ngFor="let article of articles">
          <div class="card mb-4">
            <img [src]="article.urlToImage || 'https://via.placeholder.com/150'" class="card-img-top" alt="News Image">
            <div class="card-body">
              <h5 class="card-title">{{ article.title }}</h5>
              <p class="card-text">{{ article.description }}</p>
              <p class="card-date">Date: {{ article.publishedAt | date }}</p>
              <a [href]="article.url" class="btn custom-btn-read">Read more</a>
              <a href="#" class="btn btn-like custom-btn" >
                <i class="bi bi-hand-thumbs-up-fill"></i>
              </a>
              <a href="#" class="btn btn-like custom-btn" >
                <i class="bi bi-hand-thumbs-down-fill"></i>
              </a>
            </div>
          </div>
        </div>
      </div>

   </div>

// 4-React_Projects/demo-hackton/src/Components/Card.jsx
import React from 'react'
import { useEffect,useState } from 'react';
import axios from 'axios';
import { useParams } from 'react-router';
export default function Card({}) {
  const [newsData, setNewsData] = useState([])
  const {category}=useParams();
 const articles=newsData

  useEffect(async () => {
   var {data} =  await axios.get(`https://newsapi.org/v2/everything?q=${category}&apiKey=4f273adce8b4444f85d7356f7e04b4b4`);
   setNewsData(data.articles);
  },[0])
   
    console.log("msg " + articles)
  return (
    <div>
        <div className="container mt-5">
      <div className="row">
        {articles.map((article, index) => (
          <div className="col-md-4 col-sm-6 mb-4" key={index}>
            <div className="card h-100">
              <img src={article.urlToImage || 'https://via.placeholder.com/150'} className="card-img-top" alt={article.title} />
              <div className="card-body">
                <h5 className="card-title">{article.title}</h5>
                <p className="card-text">
                  {article.description ? article.description.substring(0, 100) + '...' : 'No description available.'}
                </p>
                <a href={article.url} target="_blank" rel="noopener noreferrer" className="btn btn-primary">Read More</a>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
      
    </div>
  )
}
