// 4-React_Projects/my_redux_based/src/Components/Accounts/login.jsx
import React from 'react';
import { Form, Button, Container, Row, Col } from 'react-bootstrap';
import { Formik } from 'formik';
import * as Yup from 'yup';
import 'bootstrap/dist/css/bootstrap.min.css';

// Define Yup validation schema
const validationSchema = Yup.object().shape({
  email: Yup.string()
    .email('Invalid email address')
    .required('Email is required'),
  password: Yup.string()
    .min(8, 'Password must be at least 8 characters')
    .required('Password is required'),
});

function LoginForm() {
  return (
    <Container className="d-flex justify-content-center align-items-center min-vh-100">
      <Row className="w-100">
        <Col md={6} lg={4} className="mx-auto">
          <div className="p-4 shadow rounded bg-light">
            <h2 className="mb-4 text-center">Login Form</h2>
            <Formik
              initialValues={{
                email: '',
                password: ''
              }}
              validationSchema={validationSchema}
              onSubmit={(values) => {
                console.log('Form Data', values);
                alert('Login Successful!');
              }}
            >
              {({
                handleSubmit,
                handleChange,
                handleBlur,
                values,
                touched,
                errors,
              }) => (
                <Form noValidate onSubmit={handleSubmit}>
                  <Form.Group className="mb-3" controlId="formEmail">
                    <Form.Label>Email</Form.Label>
                    <Form.Control
                      type="email"
                      name="email"
                      placeholder="Enter your email"
                      value={values.email}
                      onChange={handleChange}
                      onBlur={handleBlur}
                      isInvalid={touched.email && !!errors.email}
                    />
                    <Form.Control.Feedback type="invalid">
                      {errors.email}
                    </Form.Control.Feedback>
                  </Form.Group>

                  <Form.Group className="mb-3" controlId="formPassword">
                    <Form.Label>Password</Form.Label>
                    <Form.Control
                      type="password"
                      name="password"
                      placeholder="Enter your password"
                      value={values.password}
                      onChange={handleChange}
                      onBlur={handleBlur}
                      isInvalid={touched.password && !!errors.password}
                    />
                    <Form.Control.Feedback type="invalid">
                      {errors.password}
                    </Form.Control.Feedback>
                  </Form.Group>

                  <Button variant="dark" type="submit" className="w-100">
                    Login
                  </Button>

                  <div className="mt-3 text-center">
                    <span>Don't have an account? <a href="#register">Register here</a></span>
                  </div>
                </Form>
              )}
            </Formik>
          </div>
        </Col>
      </Row>
    </Container>
  );
}

export default LoginForm;

// 2-Angular_Projects/Happiest_Minds_learning_management_System/src/app/mycomponent/login/login.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CandidateService } from '../../service/candidate.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule,FormsModule,CommonModule,RouterLink],
  providers: [FormBuilder],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})

export class LoginComponent {
  loginForm: any;

  constructor(private formbuilder: FormBuilder, private userServer: CandidateService, private router:Router) {

  }

  ngOnInit() {
  this.loginForm = this.formbuilder.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  })
}

onSubmit(){
  if(this.loginForm.valid){
    console.log("success",this.loginForm.value)
    this.userServer.login(this.loginForm.value).subscribe((data)=>{console.log(data)
      if(data.length==1)
      localStorage.setItem('token',JSON.stringify(this.loginForm.value))
      this.router.navigate(['candidate'])
    },(err:any)=>{
      console.log(err)
    })
  }
  else{
    console.log("failed")
  }
}


}

 <section class=".body d-flex justify-content-center align-items-center">
        <div class="container login-container">
            <div class="login-header text-center">
                <h2>Login</h2>
                <p>Enter your credentials to access your account</p>
            </div>
            <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" class="form-control" placeholder="Email" formControlName="email">
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" id="password" class="form-control" placeholder="Password" formControlName="password">
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" id="rememberMe" class="form-check-input">
                    <label for="rememberMe" class="form-check-label">Remember Me</label>
                </div>
                <button type="submit" class="btn btn-login btn-block">Login</button>
            </form>
            <div class="text-center mt-3">
                <p>Don't have an account? <a routerLink="/Signup">Register here</a></p>
            </div>
        </div>
    </section>
